In [3]:
def my_function():
  print("Hello from a function")
my_function()

Hello from a function


In [8]:
def my_function(fname):
  print(fname + " lname")

my_function("Emil")
my_function("Tobias")
my_function("Linus")

Emil lname
Tobias lname
Linus lname


In [11]:
def my_function(fname, lname):
  print(fname + " " + lname)

my_function("Emil", "Heskey")
my_function("Tobias", "Larry")
my_function("Linus", "Mac")

Emil Heskey
Tobias Larry
Linus Mac


In [12]:
def my_function(*kids):
  print("The youngest child is " + kids[2])

my_function("Emil", "Tobias", "Linus")

The youngest child is Linus


In [13]:
def my_function(**kid):
  print("His last name is " + kid["lname"])

my_function(fname = "Tobias", lname = "Refsnes")

His last name is Refsnes


In [14]:
def my_function(country = "Norway"):
  print("I am from " + country)

my_function("Sweden")
my_function("India")
my_function()
my_function("Brazil")

I am from Sweden
I am from India
I am from Norway
I am from Brazil


In [17]:
def my_function(food):
  for x in food:
    print(x)

fruits = ["apple", "banana", "cherry"]
veges = ("dodo", "nakati")

my_function(fruits)
my_function(veges)

apple
banana
cherry
dodo
nakati


In [18]:
def my_function(x):
  return 5 * x

print(my_function(3))
print(my_function(5))
print(my_function(9))

15
25
45


In [20]:
def tri_recursion(k):
  if(k > 0):
    result = k + tri_recursion(k - 1)
    print(result)
  else:
    result = 0
  return result

print("\n\nRecursion Example Results")
tri_recursion(6)



Recursion Example Results
1
3
6
10
15
21


21

In [22]:
def tri_recursion(k):
  if(k > 0):
    result = k + tri_recursion(k - 1)
    print(result)
  else:
    result = 0
  return result

print("\n\nRecursion Example Results")
tri_recursion(8)



Recursion Example Results
1
3
6
10
15
21
28
36


36

In [1]:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
mydict = dict(thisdict)
print(mydict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}


In [4]:
from numpy import matrix
from numpy import linalg
A = matrix( [[1,2,3],[11,12,13],[21,22,23]]) # Creates a matrix.
x = matrix( [[1],[2],[3]] ) # Creates a matrix (like a column vector).
y = matrix( [[1,2,3]] ) # Creates a matrix (like a row vector).
print(A.T) # Transpose of A.
print(A*x) # Matrix multiplication of A and x.
print(A.I) # Inverse of A.
print(linalg.solve(A, x)) # Solve the linear equation system.

[[ 1 11 21]
 [ 2 12 22]
 [ 3 13 23]]
[[ 14]
 [ 74]
 [134]]
[[ 2.81474977e+14 -5.62949953e+14  2.81474977e+14]
 [-5.62949953e+14  1.12589991e+15 -5.62949953e+14]
 [ 2.81474977e+14 -5.62949953e+14  2.81474977e+14]]
[[-0.01428571]
 [-0.67142857]
 [ 0.78571429]]


In [5]:
car = {
"brand": "Ford",
"model": "Mustang",
"year": 1964
}

x = car.items()

print(x) #before the change

dict_items([('brand', 'Ford'), ('model', 'Mustang'), ('year', 1964)])


In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1
